Blog/config/routes.rb
KepplerBlog::Engine.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

	 scope :admin, :blog do
  	resources :posts do 
      get 'find/subcategories', action: :subcategories_of_cagegory, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: 'search'
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :categories do
      get '(page/:page)', action: :index, on: :collection, as: 'search'
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
  end

  scope :blog do
    get '(page/:page)', to: 'blog#index', as: :blog_listing
    get ":type/:permalink", to: 'blog#filter', as: :filter
    get "category/:category/subcategory/:subcategory", to: 'blog#filter_subcategory', as: :filter_subcategory
    get '/:permalink', to: 'blog#show', as: :blog_show_post
  end

end

Blog/app/models/keppler_blog/category.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerBlog
  class Category < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    before_save :create_permalink
    has_many :posts, dependent: :destroy
    has_many :subcategories
    accepts_nested_attributes_for :subcategories, :reject_if => :all_blank, :allow_destroy => true

    #actualizar document de elasticsearch (ojo: no sabemos si es la mejor solucion.)
    #se deberia usar __elasticsearch__.update_document pero aparantemente no funciona.
    after_commit on: [:update] do
      __elasticsearch__.index_document
    end

    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :name, :subcategories] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        subcategories: self.subcategories.map { |subcategory| subcategory.name } .join(", ")
      }.as_json
    end

    private

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

  end
  #Category.import
end

Blog/app/models/keppler_blog/post.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerBlog
  class Post < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    before_save :create_permalink
    mount_uploader :image, ImageUploader
    belongs_to :user
    belongs_to :category
    belongs_to :subcategory
    acts_as_taggable
    acts_as_taggable_on :tags
    
    validates_presence_of :title, :body, :category_id
    validates_uniqueness_of :title

    #actualizar document de elasticsearch (ojo: no sabemos si es la mejor solucion.)
    #se deberia usar __elasticsearch__.update_document pero aparantemente no funciona.
    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end
    
    def self.published
      where(public: true).order(created_at: :desc)
    end
    
    def self.filter_by_autor(autor)
      where(public: true, user: User.find_by_permalink(autor).id).order(created_at: :desc)
    end

    def self.filter_by_category(category)
      where(public: true, category: Category.find_by_permalink(category).id).order(created_at: :desc)
    end

    def self.filter_by_tag(tag)
      where(public: true).tagged_with(tag.gsub("-", " ")).order(created_at: :desc)
    end

    def self.filter_by_subcategory(category, subcategory)
      Category.find_by_permalink(category).subcategories.find_by_permalink(subcategory).posts.order(created_at: :desc)
    end

    #search para el admin
    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :title, :body, :category, :autor, :subcategory, :public, :comments, :shared, :tags], operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        title: self.title,
        body: ActionView::Base.full_sanitizer.sanitize(self.body, tags: []),
        autor: self.user.name,
        category: self.category.name,
        subcategory: self.subcategory ? self.subcategory.name : "--subcategoria",
        public: self.public ? "si--publicado" : "no--publicado",
        comments: self.comments_open ? "si--comentarios" : "no--comentarios",
        shared: self.shared_enabled ? "si--compartiendo" : "no--compartiendo",
        tags: self.tag_list.to_s
      }.as_json
    end

    private

    def create_permalink
      self.permalink = self.title.downcase.parameterize
    end

  end
  #Post.import
end

Blog/app/models/keppler_blog/subcategory.rb
module KepplerBlog
  class Subcategory < ActiveRecord::Base
  	before_save :create_permalink
  	belongs_to :category
  	has_many :posts

  	private
  	
  	def create_permalink
      self.permalink = self.name.downcase.parameterize
    end
  end
end

Blog/app/controllers/keppler_blog/application_controller.rb
module KepplerBlog
  class ApplicationController < ::ApplicationController
  end
end

Blog/app/controllers/keppler_blog/blog_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class BlogController < ApplicationController  
    layout 'frontend/application'
    before_action :set_data_widgets, only: [:index, :show, :filter, :filter_subcategory]

    def index
      @posts = Post.searching(params[:query]).where(public: true).page(@current_page).per(KepplerBlog.posts_per_page)
    end

    def show   
      @post =  Post.find_by_permalink(params[:permalink])   
    end

    def filter
      @posts = Post.send("filter_by_#{params[:type]}", params[:permalink]).page(@current_page).per(10)
      render action: 'index'
    end

    def filter_subcategory
      @posts = Post.filter_by_subcategory(params[:category], params[:subcategory]).page(@current_page).per(10)
      render action: 'index'
    end

    private

    def set_data_widgets
      @posts_recents = Post.where(public: true).order("created_at DESC").first(6)
      @categories = Category.all.order(:name)
    end

  end
end

Blog/app/controllers/keppler_blog/categories_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class CategoriesController < ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      categories = Category.searching(@query).all
      @objects, @total = categories.page(@current_page), categories.size
      redirect_to categories_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Categoría creada satisfactoriamente'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Categoría actualizada satsfactoriamente'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Categoría eliminada satisfactoriamente'
    end

    def destroy_multiple
      Category.destroy redefine_ids(params[:multiple_ids])
      redirect_to categories_path(page: @current_page, search: @query), notice: "Categorías eliminadas satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:name, subcategories_attributes: [:id, :name, :_destroy])
      end
  end
end

Blog/app/controllers/keppler_blog/posts_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class PostsController < ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource except: [:subcategories_of_cagegory]
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :set_categories, only: [:new, :edit, :update, :create]

    # GET /posts
    def index
      posts = current_user.has_role?(:autor) ? Post.searching(@query).where(user_id: current_user.id) : Post.searching(@query).all
      @objects, @total = posts.page(@current_page), posts.size
      redirect_to posts_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
      @post = Post.new(post_params.merge(user_id: current_user.id))

      if @post.save
        redirect_to @post, notice: 'Post creado satisfactoriamente'
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      @post.subcategory_id = nil if post_params[:subcategory_id].nil?
      
      if @post.update(post_params)
        redirect_to @post, notice: 'Post actualizado satisfactoriamente'
      else
        render :edit
      end
    end


    def subcategories_of_cagegory
      @category = Category.find(params[:category_id])
      @subcategories = @category.subcategories
      respond_to do |format|
         format.js {  }
      end
    end


    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post eliminado satisfactoriamente'
    end

    def destroy_multiple
      Post.destroy redefine_ids(params[:multiple_ids])
      redirect_to posts_path(page: @current_page, search: @query), notice: "Posts eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      def set_categories
        @categories = Category.order(:name)
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :body, :user_id, :category_id, :subcategory_id, :image, :public, :comments_open, :shared_enabled, :permalink, :tag_list)
      end
  end
end

Blog/app/helpers/keppler_blog/application_helper.rb
module KepplerBlog
  module ApplicationHelper
 
  end
end

Blog/app/views/keppler_blog/blog/_categories.html.haml
.container-fluid
	%p Categorias
	%ul
		- @categories.each do |category|
			- unless category.posts.count.zero?
				%li.dropdown
					= link_to filter_path('category', category.permalink), class: "dropdown-toggle #{'active' if category.permalink.eql?(params[:permalink]) or category.permalink.eql?(params[:category])}" ,"aria-expanded" => false, "aria-haspopup" => true, "data-toggle" => "dropdown disabled", :role => "button" do
						= category.name.titleize
						
					- unless category.subcategories.empty?
						%span.caret
						%ul
							- category.subcategories.each do |subcategory|
								%li
									= link_to subcategory.name, filter_subcategory_path(category.permalink, subcategory.permalink), class: "#{'active' if category.permalink.eql?(params[:category]) and subcategory.permalink.eql?(params[:subcategory])}"

Blog/app/views/keppler_blog/blog/_facebook_comments.html.haml
- if @post.comments_open
	.fb-comments{ 'data-href' => "#{request.url}",  'data-numposts' => "5", 'data-colorscheme' => "light", "data-width" => "100%", "data-version"=>"v2.4" }

Blog/app/views/keppler_blog/blog/_recents.html.haml
.blog-widget
	.blog-widget--header
		%h3.widget-title
			Recientes
	.blog-widget--body
		%ul.widget-list#recents
			- @posts_recents.each do |post|
				.post.row
					.col-lg-4{style:"padding:0"}
						.post-image
							= link_to blog_show_post_path(post.permalink) do
								= image_tag post.image
					.col-lg-8{style:"padding:0"}
						.post-title
							= link_to post.title, blog_show_post_path(post.permalink)
							%p
								= post.created_at.strftime("%d %b. %Y")
					
	

Blog/app/views/keppler_blog/blog/_search.html.haml
.blog-widget
	.blog-widget--body
		.widget-list#search
			= form_tag blog_listing_path, method: :get, :html => {:class => ""} do |f|
				= text_field_tag :query, params[:query], :placeholder => "Buscar.."

Blog/app/views/keppler_blog/blog/_sidebar.html.haml
.col-lg-4.hidden-xs
	= render 'search'
	=# Categories
	= render 'recents'
	= render 'tags'
	=# Instagram

Blog/app/views/keppler_blog/blog/_tags.html.haml
.blog-widget
	.blog-widget--header
		%h3.widget-title
			Tags
	.blog-widget--body
		%ul.widget-list#tags
			- ActsAsTaggableOn::Tag.most_used(9).each do |tag|
				%li
					= link_to filter_path("tag", tag.name.parameterize), class: "tag #{'active' if params[:permalink] and tag.name.downcase.eql?(params[:permalink].gsub("-", " ").downcase)}" do
						%i.fa.fa-tags
						= tag.name

Blog/app/views/keppler_blog/blog/_twitter_timeline.html.haml
.blog-widget
	.blog-widget--header
		%h3.widget-title
			Twitter timeline
	.blog-widget--body
		%a.twitter-timeline{ href:"https://twitter.com/#{KepplerBlog.twitter_username}", "data-widget-id"=>"#{KepplerBlog.widget_twitter_id}", "data-chrome"=>"header" } 
			= "Tweets por @#{KepplerBlog.twitter_username}"
		

Blog/app/views/keppler_blog/blog/index.html.haml
= title "Keppler Blog"
= meta_description "Bienvenidos al blog de keppler admin, aquí podras encontrar excelentes articulos sobre ruby on rails."

.container.blog#keppler-blog
	.visible-xs
		= render 'search'
	.row
		.col-lg-8.col-xs-12.col-sm-8
			.posts-wrapper
				- unless @posts.empty?
					- @posts.each do |post|
						.col-lg-12
							.post
								%h2.post-title
									= link_to post.title, blog_show_post_path(post.permalink)
						.col-lg-5
							.post
								.post-image
									= link_to blog_show_post_path(post.permalink) do
										= image_tag post.image
						.col-lg-7
							.post
								.post-body
									= sanitize(post.body, tags: []).truncate(300)
									.read-more
										= link_to "Leer más", blog_show_post_path(post.permalink), class: "btn btn-xs"
						.col-lg-12
							.post
								.post-attributes
									%ul
										%li
											%span
												%i.fa.fa-calendar
												= post.created_at.strftime("%d %b. %Y")
										%li
											%i.fa.fa-user
											= link_to post.user.name, filter_path('autor', post.user.permalink)
										%li
											%i.fa.fa-tags
											= link_to post.category.name, filter_path('category', post.category.permalink)

				- else
					%center
						No se encontraron resultados.

				= paginate @posts, :views_prefix => 'templates'

		.col-lg-4.col-sm-4.hidden-xs
			= render 'search'
			%ul.nav.nav-tabs{:role => "tablist"}
				%li.active{:role => "presentation"}
					%a{"aria-controls" => "recents", "data-toggle" => "tab", :href => "#recents", :role => "tab"} 
						%i.fa.fa-star
				%li{:role => "presentation"}
					%a{"aria-controls" => "categories", "data-toggle" => "tab", :href => "#categories", :role => "tab"} 
						%i.fa.fa-folder-open
				%li{:role => "presentation"}
					%a{"aria-controls" => "tags", "data-toggle" => "tab", :href => "#tags", :role => "tab"} 
						%i.fa.fa-tags

			.tab-content
				#recents.tab-pane.active{:role => "tabpanel"}
					= render 'recents'
				#categories.tab-pane.fade{:role => "tabpanel"}
					= render 'categories'
				#tags.tab-pane.fade{:role => "tabpanel"}
					= render 'tags'

Blog/app/views/keppler_blog/blog/show.html.haml
= title @post.title
= meta_description sanitize(@post.body, tags: []).truncate(150)

.container.blog#keppler-blog
	.posts-wrapper
		.section-title
			= link_to @post.title, blog_show_post_path(@post.permalink, popup: "true")
		.section-hr
		.row.post
			.col-lg-8.col-sm-8
				.post-image
					= link_to blog_show_post_path(@post.permalink) do
						= image_tag @post.image
				.post-attributes
					%ul
						%li
							%span
								%i.fa.fa-calendar
								= @post.created_at.strftime("%d %b. %Y")
						%li
							%i.fa.fa-user
							= link_to @post.user.name, filter_path('autor', @post.user.permalink)
						%li
							%i.fa.fa-tags
							= link_to @post.category.name, filter_path('category', @post.category.permalink)
				.col-lg-12{style:"padding: 0;"}
					.post-body
						= @post.body.html_safe
				
		
				.col-lg-12{style:"padding: 0;"}
					= render 'facebook_comments'
			.col-lg-4.col-sm-4.hidden-xs
				= render 'search'
				%ul.nav.nav-tabs{:role => "tablist"}
					%li.active{:role => "presentation"}
						%a{"aria-controls" => "recents", "data-toggle" => "tab", :href => "#recents", :role => "tab"} 
							%i.fa.fa-star
					%li{:role => "presentation"}
						%a{"aria-controls" => "categories", "data-toggle" => "tab", :href => "#categories", :role => "tab"} 
							%i.fa.fa-folder-open
					%li{:role => "presentation"}
						%a{"aria-controls" => "tags", "data-toggle" => "tab", :href => "#tags", :role => "tab"} 
							%i.fa.fa-tags

				.tab-content
					#recents.tab-pane.active{:role => "tabpanel"}
						= render 'recents'
					#categories.tab-pane.fade{:role => "tabpanel"}
						= render 'categories'
					#tags.tab-pane.fade{:role => "tabpanel"}
						= render 'tags'