Blog/config/routes.rb
KepplerBlog::Engine.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

	 scope :admin, :blog do
  	resources :posts do 
      get 'find/subcategories', action: :subcategories_of_cagegory, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: 'search'
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :categories do
      get '(page/:page)', action: :index, on: :collection, as: 'search'
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
  end

  scope :blog do
    get '(page/:page)', to: 'blog#index', as: :blog_listing
    get ":type/:permalink", to: 'blog#filter', as: :filter
    get "category/:category/subcategory/:subcategory", to: 'blog#filter_subcategory', as: :filter_subcategory
    get '/:permalink', to: 'blog#show', as: :blog_show_post
  end

end

Blog/app/models/keppler_blog/category.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerBlog
  class Category < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    before_save :create_permalink
    has_many :posts, dependent: :destroy
    has_many :subcategories
    accepts_nested_attributes_for :subcategories, :reject_if => :all_blank, :allow_destroy => true

    #actualizar document de elasticsearch (ojo: no sabemos si es la mejor solucion.)
    #se deberia usar __elasticsearch__.update_document pero aparantemente no funciona.
    after_commit on: [:update] do
      __elasticsearch__.index_document
    end

    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :name, :subcategories] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        subcategories: self.subcategories.map { |subcategory| subcategory.name } .join(", ")
      }.as_json
    end

    private

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

  end
  #Category.import
end

Blog/app/models/keppler_blog/post.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerBlog
  class Post < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    before_save :create_permalink
    mount_uploader :image, ImageUploader
    belongs_to :user
    belongs_to :category
    belongs_to :subcategory
    acts_as_taggable
    acts_as_taggable_on :tags
    
    validates_presence_of :title, :body, :category_id
    validates_uniqueness_of :title

    #actualizar document de elasticsearch (ojo: no sabemos si es la mejor solucion.)
    #se deberia usar __elasticsearch__.update_document pero aparantemente no funciona.
    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end
    
    def self.published
      where(public: true).order(created_at: :desc)
    end
    
    def self.filter_by_autor(autor)
      where(public: true, user: User.find_by_permalink(autor).id).order(created_at: :desc)
    end

    def self.filter_by_category(category)
      where(public: true, category: Category.find_by_permalink(category).id).order(created_at: :desc)
    end

    def self.filter_by_tag(tag)
      where(public: true).tagged_with(tag.gsub("-", " ")).order(created_at: :desc)
    end

    def self.filter_by_subcategory(category, subcategory)
      Category.find_by_permalink(category).subcategories.find_by_permalink(subcategory).posts.order(created_at: :desc)
    end

    #search para el admin
    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:id, :title, :body, :category, :autor, :subcategory, :public, :comments, :shared, :tags], operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        title: self.title,
        body: ActionView::Base.full_sanitizer.sanitize(self.body, tags: []),
        autor: self.user.name,
        category: self.category.name,
        subcategory: self.subcategory ? self.subcategory.name : "--subcategoria",
        public: self.public ? "si--publicado" : "no--publicado",
        comments: self.comments_open ? "si--comentarios" : "no--comentarios",
        shared: self.shared_enabled ? "si--compartiendo" : "no--compartiendo",
        tags: self.tag_list.to_s
      }.as_json
    end

    private

    def create_permalink
      self.permalink = self.title.downcase.parameterize
    end

  end
  #Post.import
end

Blog/app/models/keppler_blog/subcategory.rb
module KepplerBlog
  class Subcategory < ActiveRecord::Base
  	before_save :create_permalink
  	belongs_to :category
  	has_many :posts

  	private
  	
  	def create_permalink
      self.permalink = self.name.downcase.parameterize
    end
  end
end

Blog/app/controllers/keppler_blog/application_controller.rb
module KepplerBlog
  class ApplicationController < ::ApplicationController
  end
end

Blog/app/controllers/keppler_blog/blog_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class BlogController < ApplicationController  
    layout 'frontend/application'
    before_action :set_data_widgets, only: [:index, :show, :filter, :filter_subcategory]

    def index
      @posts = Post.searching(params[:query]).where(public: true).page(@current_page).per(KepplerBlog.posts_per_page)
    end

    def show   
      @post =  Post.find_by_permalink(params[:permalink])   
    end

    def filter
      @posts = Post.send("filter_by_#{params[:type]}", params[:permalink]).page(@current_page).per(10)
      render action: 'index'
    end

    def filter_subcategory
      @posts = Post.filter_by_subcategory(params[:category], params[:subcategory]).page(@current_page).per(10)
      render action: 'index'
    end

    private

    def set_data_widgets
      @posts_recents = Post.where(public: true).order("created_at DESC").first(6)
      @categories = Category.all.order(:name)
    end

  end
end

Blog/app/controllers/keppler_blog/categories_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class CategoriesController < ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      categories = Category.searching(@query).all
      @objects, @total = categories.page(@current_page), categories.size
      redirect_to categories_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /categories/1
    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to @category, notice: 'Categoría creada satisfactoriamente'
      else
        render :new
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Categoría actualizada satsfactoriamente'
      else
        render :edit
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Categoría eliminada satisfactoriamente'
    end

    def destroy_multiple
      Category.destroy redefine_ids(params[:multiple_ids])
      redirect_to categories_path(page: @current_page, search: @query), notice: "Categorías eliminadas satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def category_params
        params.require(:category).permit(:name, subcategories_attributes: [:id, :name, :_destroy])
      end
  end
end

Blog/app/controllers/keppler_blog/posts_controller.rb
#Generado con Keppler.
require_dependency "keppler_blog/application_controller"

module KepplerBlog
  class PostsController < ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource except: [:subcategories_of_cagegory]
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :set_categories, only: [:new, :edit, :update, :create]

    # GET /posts
    def index
      posts = current_user.has_role?(:autor) ? Post.searching(@query).where(user_id: current_user.id) : Post.searching(@query).all
      @objects, @total = posts.page(@current_page), posts.size
      redirect_to posts_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
      @post = Post.new(post_params.merge(user_id: current_user.id))

      if @post.save
        redirect_to @post, notice: 'Post creado satisfactoriamente'
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      @post.subcategory_id = nil if post_params[:subcategory_id].nil?
      
      if @post.update(post_params)
        redirect_to @post, notice: 'Post actualizado satisfactoriamente'
      else
        render :edit
      end
    end


    def subcategories_of_cagegory
      @category = Category.find(params[:category_id])
      @subcategories = @category.subcategories
      respond_to do |format|
         format.js {  }
      end
    end


    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post eliminado satisfactoriamente'
    end

    def destroy_multiple
      Post.destroy redefine_ids(params[:multiple_ids])
      redirect_to posts_path(page: @current_page, search: @query), notice: "Posts eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      def set_categories
        @categories = Category.order(:name)
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :body, :user_id, :category_id, :subcategory_id, :image, :public, :comments_open, :shared_enabled, :permalink, :tag_list)
      end
  end
end

Blog/app/helpers/keppler_blog/application_helper.rb
module KepplerBlog
  module ApplicationHelper
 
  end
end

Blog/app/views/keppler_blog/categories/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Módulo de categorías
		%p Aquí podrá gestionar todos las categorías de los posts del blog, ofrece opciones de crear, editar, eliminar y visualizar, se ofrece la opcion de agregar subcategorías a las categorías creadas para llevar un mejor control y filtrado de sus posts.

Blog/app/views/keppler_blog/categories/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to categories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @category do |f|
					.row
						= f.input :name, label: "Nombre"
						= f.simple_fields_for :subcategories do |c|
							= render 'subcategory_fields', :f => c
							
						.links.right
							= link_to_add_association 'Añadir subcategoría', f, :subcategories, class: "waves-effect waves-dark btn-flat", style: "margin-bottom:10px;"
							= f.button :submit, "Guardar", class: "btn"
						

Blog/app/views/keppler_blog/categories/_index_show.html.haml
.listing-show-header#header-category
	.actions
		- if can? :update, model
			= link_to edit_category_path(@category), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card#body-category{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @category.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @category.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.permalink")
			.display-value= @category.permalink
		- unless @category.subcategories.empty?
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.subcategories")
				.display-value.subcategory
					- @category.subcategories.each do |subcategory|
						%span.subcategory= subcategory.name
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

Blog/app/views/keppler_blog/categories/_listing.html.haml
%tr{ id: "row-#{category.id}" }
	- if can? :destroy_multiple, model
		%td.item-check{style:"width: 10%"}
			= link_to "", category_path(category), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{category.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{category.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{category.id}" }

	%td{style:"width: 85%"}
		= link_to "", category_path(category, search: @query), remote: true, class: "show-row"
		%span
			= category.name								
	%td{style:"width: 5%"}		
		= link_to category_path(category), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

Blog/app/views/keppler_blog/categories/_subcategory_fields.html.haml
.nested-fields
	= f.input :name, label: "Subcategoría", wrapper: :mf_11
	.col.s1
		= link_to_remove_association f do
			= material_icon.md_24.delete.css_class('md-dark')

Blog/app/views/keppler_blog/categories/edit.html.haml
= title "Categories - editar | #{@category.id}"
= render 'form'

Blog/app/views/keppler_blog/categories/index.html.haml
= title("Categories - Listado")
.listing.col.l9.m12.s12
	= link_to new_category_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
		= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |category|
				= render 'listing', category: category
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado categorías.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"


= link_to new_category_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
	= material_icon.md_24.add.css_class("md-light")

Blog/app/views/keppler_blog/categories/new.html.haml
= title "Categories - Nuevo"
= render 'form'

Blog/app/views/keppler_blog/categories/show.html.haml
= title "Categories | #{@category.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, model
				= link_to categories_path(@category), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, model
				= link_to edit_category_path(@category), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to categories_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @category.id.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @category.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.permalink")
					.display-value.fs-body-1.tc-black-2= @category.permalink.to_s.humanize

Blog/app/views/keppler_blog/categories/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@category.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");