Catalog/config/routes.rb
KepplerCatalogs::Engine.routes.draw do
  
  
  
  scope :admin do

  	resources :catalogs do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      resources :attachments do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
    end

    scope :attachment do
    	resources :categories do
    		get '(page/:page)', action: :index, on: :collection, as: ''
      		delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    	end
    end
  end


    
end

Catalog/app/models/keppler_catalogs/attachment.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerCatalogs
  class Attachment < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    belongs_to :catalog
    before_save :create_permalink
    mount_uploader :image, CoverUploader
    validates_uniqueness_of :name
    validates_presence_of :name


    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end

    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:name, :description, :public] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        description: ActionView::Base.full_sanitizer.sanitize(self.description, tags: []),
        public:  self.public ? "publicado" : "no--publicado"
      }.as_json
    end

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

    def remove_image_public
      if !self.image_url.nil? and self.upload != "1"
        image = File.dirname(Rails.root.join("public"+self.image_url))
        FileUtils.rm_rf(image)
      end
    end
  end
  #Attachment.import
end

Catalog/app/models/keppler_catalogs/catalog.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerCatalogs
  class Catalog < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    before_save :create_permalink
    has_many :attachments, :dependent => :destroy
    validates_presence_of :name
    validates_uniqueness_of :name
    validates_length_of :name, :minimum => 1, :maximum => 15

    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end

    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:name, :description] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name.to_s,
        description: ActionView::Base.full_sanitizer.sanitize(self.description, tags: [])
      }.as_json
    end

    def published_files
      self.attachments.where(public: true)
    end

    def published_files_count
      self.attachments.where(public: true).count
    end

    private

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

  end
  #Catalog.import
end

Catalog/app/controllers/keppler_catalogs/application_controller.rb
module KepplerCatalogs
  class ApplicationController < ActionController::Base
  end
end

Catalog/app/controllers/keppler_catalogs/attachments_controller.rb
#Generado con Keppler.
require_dependency "keppler_catalogs/application_controller"

module KepplerCatalogs
  class AttachmentsController < ::ApplicationController
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_attachment, only: [:show, :edit, :update, :destroy]
    before_action :set_catalog

    # GET /attachments
    def index
      attachments = Attachment.searching(@query).where({catalog_id: params[:catalog_id]}).all
      @objects, @total = attachments.page(@current_page), attachments.size
      redirect_to attachments_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /attachments/1
    def show
    end

    # GET /attachments/new
    def new
      @attachment = Attachment.new
    end

    # GET /attachments/1/edit
    def edit
    end

    # POST /attachments
    def create
      @attachment = Attachment.new(attachment_params)
      @attachment.catalog_id = params[:catalog_id]

      if @attachment.save
        redirect_to catalog_attachments_path, notice: 'Archivo creado satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /attachments/1
    def update
      if @attachment.update(attachment_params)
        redirect_to catalog_attachments_path, notice: 'Archivo editado satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /attachments/1
    def destroy
      @attachment.destroy
      redirect_to catalog_attachments_url, notice: 'Archivo eliminado satisfactoriamente.'
    end

    def destroy_multiple
      Attachment.destroy redefine_ids(params[:multiple_ids])
      redirect_to catalog_attachments_path(page: @current_page, search: @query), notice: "Archivo eliminados satisfactoriamente"
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_attachment
        @attachment = Attachment.find(params[:id])
      end

      def set_catalog
        @catalog = Catalog.find_by_id(params[:catalog_id]).nil? ? redirect_to("/404") : Catalog.find(params[:catalog_id])
      end

      # Only allow a trusted parameter "white list" through.
      def attachment_params
        params.require(:attachment).permit(:name, :description, :aditional_text, :image, :public, :permalink)
      end
  end
end

Catalog/app/controllers/keppler_catalogs/catalogs_controller.rb
#Generado con Keppler.
require_dependency "keppler_catalogs/application_controller"

module KepplerCatalogs
  class CatalogsController < ::ApplicationController
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_catalog, only: [:show, :edit, :update, :destroy]

    # GET /catalogs
    def index
      catalogs = Catalog.searching(@query).all
      @objects, @total = catalogs.page(@current_page), catalogs.size
      redirect_to catalogs_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /catalogs/1
    def show
    end

    # GET /catalogs/new
    def new
      @catalog = Catalog.new
    end

    # GET /catalogs/1/edit
    def edit
    end

    # POST /catalogs
    def create
      @catalog = Catalog.new(catalog_params)

      if @catalog.save
        redirect_to catalogs_path, notice: 'Catálogo creado satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /catalogs/1
    def update
      if @catalog.update(catalog_params)
        redirect_to catalogs_path, notice: 'Catálogo editar satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /catalogs/1
    def destroy
      @catalog.destroy
      redirect_to catalogs_url, notice: 'Catálogo eliminar satisfactoriamente.'
    end

    def destroy_multiple
      Catalog.destroy redefine_ids(params[:multiple_ids])
      redirect_to catalogs_path(page: @current_page, search: @query), notice: "Catalogos eliminados satisfactoriamente"
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_catalog
        @catalog = Catalog.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def catalog_params
        params.require(:catalog).permit(:name, :description, :public, :permalink)
      end
  end
end

Catalog/app/helpers/keppler_catalogs/application_helper.rb
module KepplerCatalogs
  module ApplicationHelper
  end
end

Catalog/app/helpers/keppler_catalogs/attachments_helper.rb
module KepplerCatalogs
  module AttachmentsHelper
  end
end

Catalog/app/helpers/keppler_catalogs/catalogs_helper.rb
module KepplerCatalogs
  module CatalogsHelper
  end
end

Catalog/app/helpers/keppler_catalogs/categories_helper.rb
module KepplerCatalogs
  module CategoriesHelper
  end
end

Catalog/app/views/keppler_catalogs/attachments/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.perm_media.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 
			= t("model.#{controller_name.singularize}.description.title")
		%p{align:"justify"} 
			= t("model.#{controller_name.singularize}.description.body")

Catalog/app/views/keppler_catalogs/attachments/_form.html.haml
- (action_name == "new" or action_name == "create") ? action="create" : action="update"
.wrapper
	.wrapper-body.container
		.actions
			= link_to catalog_attachments_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @attachment, :url => url_for(:action => action, :controller => 'attachments') do |f|
					.row
						= f.input :name, label: t("model.#{controller_name.singularize}.attributes.name")

						= f.input :image,label: t("model.#{controller_name.singularize}.attributes.image"), :as => :file_material, label: false, wrapper_html: { class: "file-field" }

						- unless @attachment.catalog_id == 1
							= f.input :description, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }

						- if @attachment.catalog_id == 2
							= f.input :aditional_text, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }

						= f.input :public, label: "Publicar", as: :checkbox_material

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

- if @attachment.image.file
	:javascript
		$('.file-path').val("#{@attachment.image}")

Catalog/app/views/keppler_catalogs/attachments/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, model
			= link_to edit_catalog_attachment_path(params[:catalog_id], @attachment), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.perm_media.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	- if @attachment.image?
		= image_tag @attachment.image
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @attachment.name
		- unless @attachment.description.blank?
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.description")
				.display-value= sanitize(@attachment.description, tags: []).truncate(300)
		- unless @attachment.aditional_text.blank?
			%li.list-row
				.display-label= t("model.#{controller_name.singularize}.attributes.aditional_text")
				.display-value= sanitize(@attachment.aditional_text, tags: []).truncate(300)
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.public")
			.display-value= @attachment.public? ? "Si" : "No"

:javascript
	$('.tooltipped').tooltip({delay: 1});

Catalog/app/views/keppler_catalogs/attachments/_listing.html.haml
%tr{ id: "row-#{attachment.id}" }
	- if can? :destroy_multiple, model
		%td.item-check{style:"width: 10%"}
			= link_to "", catalog_attachment_path(params[:catalog_id], attachment), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{attachment.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{attachment.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{attachment.id}" }

	%td{style:"width: 30%"}
		= link_to "", catalog_attachment_path(params[:catalog_id], attachment.id, search: @query), remote: true, class: "show-row"
		%span
			= attachment.name

	%td{style:"width: 30%"}
		= link_to "", catalog_attachment_path(params[:catalog_id], attachment, search: @query), remote: true, class: "show-row"
		%span
			- if attachment.public?
				Publicado
			- else
				No Publicado

	%td{style:"width: 5%"}
		= link_to catalog_attachment_path(params[:catalog_id], attachment), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

Catalog/app/views/keppler_catalogs/attachments/_mediaframe.html.haml
- if attachment.image?
	= image_tag attachment.image, style:"#{style}"

Catalog/app/views/keppler_catalogs/attachments/edit.html.haml
= title "Archivo - editar | #{@attachment.id}"
= header_information do
	= link_to "Catálogos", catalogs_path
	= ">"
	= link_to "#{@catalog.name.humanize}", catalog_attachments_path
	= "> #{@attachment.name.humanize}"

= render 'form'

Catalog/app/views/keppler_catalogs/attachments/index.html.haml
= title("#{@catalog.name.humanize} - Archivos - Listado")

//change header information
= header_information do
	= link_to "Catálogos", catalogs_path
	= "> #{@catalog.name.humanize}"

.listing.col.l9.m12.s12
	- if can? :new, KepplerCatalogs::Attachment
		= link_to new_catalog_attachment_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only", "data-no-turbolink" => false do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |attachment|
				= render 'listing', attachment: attachment
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t("model.#{controller_name.singularize}.no_found.text")
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, KepplerCatalogs::Attachment
	= link_to new_catalog_attachment_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red", "data-no-turbolink" => false do
		= material_icon.md_24.add.css_class("md-light")

Catalog/app/views/keppler_catalogs/attachments/new.html.haml
= title "Archivo - Nuevo"
= header_information do
	= link_to "Catálogos", catalogs_path
	= "> #{@catalog.name.humanize} "
= render 'form'

Catalog/app/views/keppler_catalogs/attachments/show.html.haml
= title "Archivo | #{@attachment.id}"
= header_information do
	= link_to "Catálogos", catalogs_path
	= ">"
	= link_to "#{@catalog.name.humanize}", catalog_attachments_path
	= "> #{@attachment.name.humanize}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, model
				= link_to catalog_attachment_path(params[:catalog_id], @attachment), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, model
				= link_to edit_catalog_attachment_path(params[:catalog_id], @attachment), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to catalog_attachments_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card{style: "padding: 0px"}
			.card-image
				- if @attachment.image?
					= image_tag @attachment.image
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @attachment.name.humanize
					- unless @attachment.description.blank?
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.description")
							.display-value.fs-body-1.tc-black-2= @attachment.description.html_safe
					- unless @attachment.aditional_text.blank?
						%li.list-row
							.display-label= t("model.#{controller_name.singularize}.attributes.aditional_text")
							.display-value.fs-body-1.tc-black-2= @attachment.aditional_text.html_safe
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.public")
						.display-value.fs-body-1.tc-black-2= @attachment.public? ? "Si" : "No"

Catalog/app/views/keppler_catalogs/attachments/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@attachment.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");

Catalog/app/views/keppler_catalogs/catalogs/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.perm_media.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 
			= t("model.#{controller_name.singularize}.description.title")
		%p{align:"justify"} 
			= t("model.#{controller_name.singularize}.description.body")

Catalog/app/views/keppler_catalogs/catalogs/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to catalogs_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @catalog do |f|
					.row

						= f.input :name, label: t("model.#{controller_name.singularize}.attributes.name")
						= f.input :description, label: t("model.#{controller_name.singularize}.attributes.description"), :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

Catalog/app/views/keppler_catalogs/catalogs/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :index, KepplerCatalogs::Attachment
			= link_to catalog_attachments_path(@catalog), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Ir a archivos", "data-no-turbolink" => false do
				= material_icon.md_24.perm_media
		- if can? :update, KepplerCatalogs::Catalog
			= link_to edit_catalog_path(@catalog), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.perm_media.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @catalog.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= sanitize(@catalog.description, tags: []).truncate(300)
		%li.list-row
			.display-label Archivos contenidos
			.display-value= @catalog.attachments.count


:javascript
	$('.tooltipped').tooltip({delay: 1});

Catalog/app/views/keppler_catalogs/catalogs/_listing.html.haml
%tr{ id: "row-#{catalog.id}" }
	- if can? :destroy_multiple, model
		%td.item-check{style:"width: 10%"}
			= link_to "", catalog_path(catalog), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{catalog.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{catalog.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{catalog.id}" }

	%td{style:"width: 10%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span
			= material_icon.md_24.folder_open
	%td{style:"width: 30%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span
			= catalog.name

	%td{style:"width: 5%"}
		= link_to "#", class: "btn-floating waves-effect waves-light btn-flat dropdown-button", "data-activates" => "catalog-options-#{catalog.id}" do
			= material_icon.md_24.more_vert.css_class("md-dark")
		%ul{ id: "catalog-options", class: "dropdown-content dropdow-content-listing", id: "catalog-options-#{catalog.id}"}
			%li
				= link_to 'Ver detallado', catalog_path(catalog)
			%li
				= link_to 'Ir a archivos', catalog_attachments_path(catalog)

Catalog/app/views/keppler_catalogs/catalogs/edit.html.haml
= title "Catálogo - editar | #{@catalog.id}"
= render 'form'

Catalog/app/views/keppler_catalogs/catalogs/index.html.haml
= title("Catálogos - Listado")
.listing.col.l9.m12.s12
	- if can? :new, KepplerCatalogs::Catalog
		= link_to new_catalog_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
		= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |catalog|
				= render 'listing', catalog: catalog
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t("model.#{controller_name.singularize}.no_found.text")
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, KepplerCatalogs::Catalog
	= link_to new_catalog_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

Catalog/app/views/keppler_catalogs/catalogs/new.html.haml
= title "Catálogo - Nuevo"
= render 'form'

Catalog/app/views/keppler_catalogs/catalogs/show.html.haml
= title "Catálogo | #{@catalog.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, model
				= link_to catalog_path(@catalog), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: '¿Estas seguro de querer eliminar?' } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, model
				= link_to edit_catalog_path(@catalog), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
					= material_icon.md_18.create.css_class("md-dark")
			- if can? :index, KepplerCatalogs::Attachment
				= link_to catalog_attachments_path(@catalog), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Ir a archivos" do
					= material_icon.md_18.perm_media.css_class("md-dark")
			= link_to catalogs_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card{style: "padding: 0px"}
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @catalog.name.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @catalog.description.html_safe

Catalog/app/views/keppler_catalogs/catalogs/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@catalog.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");

Catalog/app/views/layouts/keppler_catalogs/_links.html.haml
- if can? :index,  KepplerCatalogs::Catalog
	%li
		= header_tab t('model.plural.catalogs'), "perm_media", current_navigation?("KepplerCatalogs")
		= body_tab do
			- if can? :index, KepplerCatalogs::Catalog
				= link_tab "Lista de catálogos", '/admin/catalogs', current_navigation?("KepplerCatalogs::Catalogs")